/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Poppins', 'sans-serif'],
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        'dark-grey': '#6B6B6B',
        'dark-medium-grey': '#949494',
        'medium-grey': '#A7A7A7',
        'very-light-grey': '#F5F5F5',
        'light-grey': '#CDCDCD',
        'pure-black': '#000000',
        'main-black': '#131313',
        'pure-white': '#FFFFFF',
        'main-white': '#F8FAFB',
        'red': '#E0475F',
        'green': '#17BF97',
        'yellow': '#F6C90E',
        'accent': '#BC31EA',
        'purple': '#C54AE2',
        'dark-blue': '#1C274C',
        'blue': '#3871E0',
        'light-yellow': '#E4DB8C',
        'dark-brown': '#443600',
        'primary': '#F6C90E',
        'secondary': '#131313',
        'tertiary': '#F8FAFB',
        'quaternary': '#C54AE2',
        'success': '#17BF97',
        'error': '#E0475F',
        'disabled-bg': '#A7A7A7',
        'disabled-fg': '#6B6B6B',
        'text-on-colored': '#443600',
        'loading-bg': '#E4DB8C',
      },
    },
  },
  plugins: [],
};
